version: '3.8'

services:
  server: 
    image: nginx:1.18
    container_name: laravel-nginx
    hostname: nginx
    restart: always
    ports: 
      - "8080:80"
    networks: 
      - laravel
    volumes: 
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./source/:/home/www/

  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile 
    container_name: laravel_php
    hostname: php
    working_dir: /home/www/
    entrypoint: ./entrypoint.sh
    volumes: 
      - ./source/:/home/www/
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
    expose:
      - "9000"
    networks: 
      - laravel

  db:
    image: mysql:8.0.30
    container_name: laravel-mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports: 
      - "3306:3306"
    networks: 
      - laravel
    volumes:
      - laravel:/var/lib/mysql

networks: 
  laravel:

volumes:
  laravel: