FROM php:8.1-fpm-alpine

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Install extensions
RUN docker-php-ext-install pdo_mysql

WORKDIR /home/www/

COPY . /home/www/

RUN composer install

RUN composer install

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]